on: push
name: ğŸš€ Deploy website on push

jobs:
  web-deploy:
    name: ğŸ‰ Deploy to Strato ssh
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v3
    
    - name: ï¿½ï¸ Clean remote directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        script: |
          rm -rf /Math-Nodes/*
    
    - name: ï¿½ğŸ“‚ Sync files
      uses: wlixcc/SFTP-Deploy-Action@v1.2.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        remote_path: '/Math-Nodes/'
        sftp_only: true
        local_path: './'
        port: ${{ secrets.FTP_PORT }}